import '../../config/node-app.rake'

$remote = 'hestia.rethinkdb.com'
$root = '/srv/www/mobile.checkin.hestia.rethinkdb.com/'
$script_name = 'server.js'
$app_name = 'Meetup demo: mobile check-in'
$user = 'michael'
$required_files = []
$directories_required = [
    "app",
]
$app_files_to_copy = [
    "app/package.json",
    "app/#{$script_name}",
    "app/static",
]
$app_files_to_exclude = [
    ".DS_Store",
    ".webassets-cache",
    ".sass-cache",
]
$node_binary = "/home/michael/.nvm/v0.11.13/bin/node -- harmony"

desc 'Restart the RethinkDB server'
task :restart_rethinkdb do
    ssh('sudo service rethinkdb restart', interactive: true)
end
