import '../../config/node-app.rake'

# TODO: access variables from the imported Rakefile and add to the list of required commands
#puts $required_commands
#$required_commands << 'rethinkdb'

$remote = 'hestia.rethinkdb.com'
$root = '/srv/www/mobile.checkin.hestia.rethinkdb.com/'
$virtualenv_dir = 'env'
$script_name = 'server.js'
$app_name = 'Meetup demo: mobile check-in'
# File that has to exist before the app can run (manually add these files)
$required_files = []
# User to ssh / scp as, must have sudo access
$user = 'michael'
# App files that should be copied when the app is updated
$app_files_to_copy = [
    "app/package.json",
    "app/#{$script_name}",
    "app/static",
]
# Patten of files to exclude when copying app files
$app_files_to_exclude = [
    ".DS_Store",
    ".webassets-cache",
    ".sass-cache",
]
# Directories that should exist before the app can run (on init)
$directories_required = [
    "app",
]

desc 'Restart the RethinkDB server'
task :restart_rethinkdb do
    ssh('sudo service rethinkdb restart', interactive: true)
end
