import '../config/python-app.rake'

$remote = 'hestia.rethinkdb.com'
$root = '/srv/www/meetup.hestia.rethinkdb.com/'
$virtualenv_dir = 'env'
$script_name = 'hestia.py'
$app_name = 'Hestia meetup service'
# File that has to exist before the app can run (manually add these files)
$required_files = [
    "app/config.yaml",
]
# User to ssh / scp as, must have sudo access
$user = 'michael'
# App files that should be copied when the app is updated
$app_files_to_copy = [
    "app/requirements.txt",
    "app/#{$script_name}",
    "app/config.example.yaml",
    "app/dymo-templates",
    "app/static",
    "app/templates",
]
# Patten of files to exclude when copying app files
$app_files_to_exclude = [
    ".DS_Store",
    ".webassets-cache",
    ".sass-cache",
]
# Directories that should exist before the app can run (on init)
$directories_required = [
    "app",
    "logs",
]
