import '../config/python-app.rake'

$required_commands = ['nginx', 'pip', 'virtualenv']
$remote = 'hestia.rethinkdb.com'
$remote_port = '440'
$root = '/srv/www/meetup.hestia.rethinkdb.com/'
$virtualenv_dir = 'env'
$user = 'michael'
$script_name = 'hestia.py'
$app_name = 'Hestia meetup service'
$required_files = [
    "app/config.yaml",
]
$app_files_to_copy = [
    "app/requirements.txt",
    "app/#{$script_name}",
    "app/config.example.yaml",
    "app/dymo-templates",
    "app/static",
    "app/templates",
]
$app_files_to_exclude = [
    ".DS_Store",
    ".webassets-cache",
    ".sass-cache",
]
