import '../../config/python-app.rake'

$required_commands = ['nginx', 'pip', 'virtualenv']
$remote = 'hestia.rethinkdb.com'
$remote_port = '440'
$root = '/srv/www/cds.hestia.rethinkdb.com/'
$virtualenv_dir = 'env'
$user = 'michael'
$script_name = 'capsule-data-service.py'
$app_name = 'Capsule data service'
$required_files = [
    "app/config.yaml",
]
$app_files_to_copy = [
    "app/requirements.txt",
    "app/#{$script_name}",
    "app/config.example.yaml",
]
$app_files_to_exclude = [
    ".webassets-cache",
    ".sass-cache",
]
