import '../../config/python-app.rake'

$remote = 'hestia.rethinkdb.com'
$root = '/srv/www/cds.hestia.rethinkdb.com/'
$virtualenv_dir = 'env'
$script_name = 'capsule-data-service.py'
$app_name = 'Capsule data service'
# File that has to exist before the app can run (manually add these files)
$required_files = [
    "app/config.yaml",
]
# User to ssh / scp as, must have sudo access
$user = 'michael'
# App files that should be copied when the app is updated
$app_files_to_copy = [
    "app/requirements.txt",
    "app/#{$script_name}",
    "app/config.example.yaml",
]
