import '../../config/python-app.rake'

$required_commands = ['rethinkdb', 'nginx', 'pip', 'virtualenv']
$remote = 'hestia.rethinkdb.com'
$remote_port = '440'
$root = '/srv/www/server.checkin.hestia.rethinkdb.com/'
$virtualenv_dir = 'env'
$user = 'michael'
$script_name = 'seed-data.py'
$app_name = 'Meetup demo: data seed service'
$required_files = []
$app_files_to_copy = [
    "app/requirements.txt",
    "app/#{$script_name}",
]
$app_files_to_exclude = [
    ".DS_Store",
    ".webassets-cache",
    ".sass-cache",
    "meetups.json",
    "rethinkdb_data",
]

desc 'Restart the RethinkDB server'
task :restart_rethinkdb do
    ssh('sudo service rethinkdb restart', interactive: true)
end
